/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoHospede;
import fatec.poo.model.Hospede;
import javax.swing.JOptionPane;

/**
 *
 * @author mateu
 */
public class GuiCadastroHospede extends javax.swing.JFrame {

    /**
     * Creates new form GuiCadastroHospede
     */
    public GuiCadastroHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblTaxaDesc = new javax.swing.JLabel();
        jtxtTaxaDesc = new javax.swing.JTextField();
        jtxtTelefone = new javax.swing.JTextField();
        jtxtEndereco = new javax.swing.JTextField();
        jtxtNome = new javax.swing.JTextField();
        jtxtCPF = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Hóspede");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCpf.setText("CPF");

        lblNome.setText("Nome");

        lblEndereco.setText("Endereço");

        lblTelefone.setText("Telefone");

        lblTaxaDesc.setText("Taxa de desconto (%)");

        jtxtTaxaDesc.setEnabled(false);

        jtxtTelefone.setEnabled(false);

        jtxtEndereco.setEnabled(false);

        jtxtNome.setEnabled(false);

        try {
            jtxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Email");

        txtEmail.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaxaDesc)
                            .addComponent(lblTelefone)
                            .addComponent(lblEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblCpf))
                            .addComponent(lblNome)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTaxaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(jtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(jtxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaDesc)
                    .addComponent(jtxtTaxaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD2211023","BD2211023");//usuario e senha
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");
        daoHospede = new DaoHospede(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cpf = jtxtCPF.getText();
        if(!Hospede.validarCPF(cpf)){
            JOptionPane.showMessageDialog(this, "CPF invalido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            hospede = null;
            hospede = daoHospede.consultar(jtxtCPF.getText());

            if (hospede == null){ // não encontrou no BD
                jtxtCPF.setEnabled(false);
                jtxtNome.setEnabled(true);
                txtEmail.setEnabled(true);
                jtxtEndereco.setEnabled(true);
                jtxtTelefone.setEnabled(true);
                jtxtTaxaDesc.setEnabled(true);
                jtxtNome.requestFocus();

                btnConsultar.setEnabled(false);
                btnInserir.setEnabled(true);
            }
            else{ //encontrou o objeto na BD
               jtxtNome.setText(hospede.getNome());
               txtEmail.setText(hospede.getEmail());
               jtxtEndereco.setText(hospede.getEndereco());
               jtxtTelefone.setText(hospede.getTelefone());
               jtxtTaxaDesc.setText(String.valueOf(hospede.getTaxaDesconto()));

               jtxtCPF.setEnabled(false);
               jtxtNome.setEnabled(true);
               txtEmail.setEnabled(true);
               jtxtEndereco.setEnabled(true);
               jtxtTelefone.setEnabled(true);
               jtxtTaxaDesc.setEnabled(true);
               jtxtNome.requestFocus();

               btnConsultar.setEnabled(false);
               btnAlterar.setEnabled(true);
               btnExcluir.setEnabled(true);
            }
       }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
        // Validação dos campos antes de inserir
        if (jtxtNome.getText().isEmpty() || jtxtEndereco.getText().isEmpty() || jtxtTelefone.getText().isEmpty() || jtxtTaxaDesc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de inserir.");
            return;
        }

        double taxaDesconto = Double.parseDouble(jtxtTaxaDesc.getText());
        if (taxaDesconto < 0 || taxaDesconto > 100) {
            JOptionPane.showMessageDialog(null, "A taxa de desconto deve estar entre 0 e 100.");
            return;
        }

        hospede = new Hospede(jtxtCPF.getText(), jtxtNome.getText());
        hospede.setEmail(txtEmail.getText());
        hospede.setTaxaDesconto(taxaDesconto);
        hospede.setEndereco(jtxtEndereco.getText());
        hospede.setTelefone(jtxtTelefone.getText());
        daoHospede.inserir(hospede);

        jtxtCPF.setText("");
        jtxtNome.setText("");
        txtEmail.setText("");
        jtxtEndereco.setText("");
        jtxtTelefone.setText("");
        jtxtTaxaDesc.setText("");
        jtxtCPF.setEnabled(true);
        jtxtNome.setEnabled(false);
        txtEmail.setEnabled(false);
        jtxtEndereco.setEnabled(false);
        jtxtTelefone.setEnabled(false);
        jtxtTaxaDesc.setEnabled(false);
        jtxtCPF.requestFocus();

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Erro ao converter números. Verifique os campos.");
    }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
        // Validação dos campos antes de alterar
        if (jtxtNome.getText().isEmpty() || jtxtEndereco.getText().isEmpty() || jtxtTelefone.getText().isEmpty() || jtxtTaxaDesc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de alterar.");
            return;
        }

        double taxaDesconto = Double.parseDouble(jtxtTaxaDesc.getText());
        if (taxaDesconto < 0 || taxaDesconto > 100) {
            JOptionPane.showMessageDialog(null, "A taxa de desconto deve estar entre 0 e 100.");
            return;
        }

        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) { // Sim
            hospede.setEndereco(jtxtEndereco.getText());
            hospede.setTelefone(jtxtTelefone.getText());
            hospede.setTaxaDesconto(taxaDesconto);
            hospede.setNome(jtxtNome.getText());
            daoHospede.alterar(hospede);
        }         

        jtxtCPF.setText("");
        jtxtNome.setText("");
        txtEmail.setText("");
        jtxtEndereco.setText("");
        jtxtTelefone.setText("");
        jtxtTaxaDesc.setText("");
        jtxtCPF.setEnabled(true);
        jtxtNome.setEnabled(false);
        txtEmail.setEnabled(false);
        jtxtEndereco.setEnabled(false);
        jtxtTelefone.setEnabled(false);
        jtxtTaxaDesc.setEnabled(false);
        jtxtCPF.requestFocus();

        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Erro ao converter números. Verifique os campos.");
    }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
        daoHospede.excluir(hospede.getCpf());
    }
    
    jtxtCPF.setText("");
    jtxtNome.setText("");
    txtEmail.setText("");
    jtxtEndereco.setText("");
    jtxtTelefone.setText("");
    jtxtTaxaDesc.setText("");
    jtxtCPF.setEnabled(true);
    jtxtNome.setEnabled(false);
    txtEmail.setEnabled(false);
    jtxtEndereco.setEnabled(false);
    jtxtTelefone.setEnabled(false);
    jtxtTaxaDesc.setEnabled(false);
    jtxtCPF.requestFocus();

    btnConsultar.setEnabled(true);
    btnAlterar.setEnabled(false);
    btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField jtxtCPF;
    private javax.swing.JTextField jtxtEndereco;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtTaxaDesc;
    private javax.swing.JTextField jtxtTelefone;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTaxaDesc;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
    private DaoHospede daoHospede = null;
    private Conexao conexao=null;
    private Hospede hospede=null;
}
